import Head from "next/head";
import Link from "next/link";
import React from "react";

type LayoutProps = {
  title?: string;
  children: any;
};

const Layout: React.FC<LayoutProps> = ({ title, children }) => {
  const icb = "Ingeniería Científica Bionanomolecular SA de CV";

  return (
    <>
      <Head>
        <title>{title ? `${title} - ${icb}` : icb}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex min-h-screen flex-col justify-between">
        <header>
          <nav className="flex h-12 items-center justify-between shadow-md">
            <Link href="/" className="px-5 text-lg font-bold">
              Inicio
            </Link>
            <div>
              <Link href="/cart" className="px-5">
                Carrito
              </Link>
            </div>
          </nav>
        </header>
        <main className="container m-auto mt-4 px-4">{children}</main>
        <footer className="flex h-10 items-center justify-center shadow-inner">
          Copyright © 2022 {icb}
        </footer>
      </div>
    </>
  );
};

export default Layout;
